// TODO: add necessary imports
import { useState, useEffect } from 'react';


const fetchData = async ( url, options = {}) => {
  // console.log('fetching data from url: ', url);
  const response = await fetch(url, options);
  const json = await response.json();
  if (!response.ok) {
    // console.log('json', json);
    if (json.message) {
      throw new Error(json.message);
    }
    throw new Error(`Error ${response.status} occured`);
  }
  return json;
};



const useMedia = () => {


const [mediaArray, setMediaArray] = useState([]);


const getMedia = async () => {
  const url = import.meta.env.VITE_MEDIA_API + '/media';
  try{
    const mediaData = await fetchData(url);

    const newArray = await Promise.all(
      mediaData.map(async (item) => {
        const userUrl = import.meta.env.VITE_AUTH_API + '/users/' + item.user_id;
        const user = await fetchData(userUrl);

        return{
          ...item,
          username: user.username,
        };
      })
    );



    setMediaArray(newArray);
    //console.log(newArray);
  }
  catch (error){
    console.log('Error fetching data: ', error);
  }
};



 const postMedia = async (file, inputs, token) => {
  try{
    
    
    
    // TODO: create a suitable object for Media API: without media_id, user_id, thumbnail and created_at. All those are generated by the API. See the media API documentation.
    const mediaData = {
      title: inputs.title,               // use correct field
      description: inputs.description,
      filename: file.filename,
      media_type: file.media_type,
      filesize: file.filesize,
     }

     // TODO: post the data to Media API and get the data as MediaResponse
     const response = await fetch(import.meta.env.VITE_MEDIA_API + '/media', {
      method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(mediaData)
     });

     if(!response.ok){
      throw new Error('MediaFile upload failed.');
     }

    // TODO: return the data
     const data = await response.json();
     return data;
  }

  catch(error){
    console.log('Error in postMedia', error);
    throw error;
  }
     
     
 };





 useEffect(() => {
  getMedia();
 }, []);

 
return {mediaArray, postMedia};
};





const useAuthentication = () => {

   const postLogin = async (inputs) => {
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(inputs),
    };
    const loginResult = await fetchData(import.meta.env.VITE_AUTH_API + '/auth/login', fetchOptions);
    return loginResult;
  };



  return { postLogin }


}


const useUser = () => {

  const getUserByToken = async (token) =>{
    try{
      const fetchOptions = {
        method: 'GET',
        headers: {
          'Authorization': `Bearer ${token}`
        },
      };

      const useUserResult = await fetchData(import.meta.env.VITE_AUTH_API + '/users/token', fetchOptions);
      return useUserResult;
    }
    catch(error){
      console.log('Error in useUser', error);
    }
  };


  const postUser = async (inputs) =>{
    try{
      const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(inputs),
    };
    const registerResult = await fetchData(import.meta.env.VITE_AUTH_API + '/users', fetchOptions);
    return registerResult;



    }catch(error){
      console.log('Error in postUser', error);
    }
    
    }


  return { getUserByToken, postUser }
}


const useFile = () => {

   const postFile = async (file, token) => {

    try{
      // TODO: create FormData object
      const formData = new FormData();

      // TODO: add file to FormData
      formData.append('file', file);

      const response = await fetch(import.meta.env.VITE_UPLOAD_SERVER + '/upload', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`
        },
        body: formData
      });

      if(!response.ok){
        throw new Error('File upload failed.');
      }

      const data = await response.json();
      return data;
    }
    catch(error){
      console.log('Error in postFile: ', error);
    }
     
     
     // TODO: upload the file to file server and get the file data, use upload api endpoint
     // - add authorization header with token, content-type is set automatically when using FormData
     // TODO: return the file data.
 };

 return { postFile }

}



   
export {useMedia, useAuthentication, useUser, useFile};