'use strict';

//TODO: everything here


//example datastructure
import promisePool from "../../utils/database.js";

const default_discount = {
    id : 0,     //auto generated by backend
    discount: 0.9,  //Esim 10% alennus, alkuperäinen hinta * 0.9
    discount_code : "code which activates the discount at checkout",
    date_start: "2025-12-06",
    date_end: "2025-12-06",
    message: "default discount"
}



/**
 *
 * @return {Promise<[{id: number, target_meal: number, cost_override: number, discount_code: string, date_start: string, date_end: string, message: string},{id: number, target_meal: number, cost_override: number, discount_code: string, date_start: string, date_end: string, message: string},{id: number, target_meal: number, cost_override: number, discount_code: string, date_start: string, date_end: string, message: string}]|boolean>}
 * array of all objects or false if error
 */
const listAllDiscounts = async () => {
    try {
        console.log('listAllDiscounts in discount-model');
        const [discountArray] = await promisePool.query('SELECT * FROM discounts');
        //console.log('discountArray:', discountArray);
        return discountArray;

    } catch (error) {
        console.log('error in listAllDiscounts in discount-model');
        console.log(error);
        return false;
    }
};

/**
 *
 * @param id
 * @return {Promise<*|boolean>}
 * first object that has the id or false if not found or error
 */
const findDiscountById = async (id) => {
    try {
        console.log('findDiscountById in discount-model');
        const query = promisePool.format('SELECT * FROM discounts where id = ?', id);
        const [discountArray] = await promisePool.execute(query);


        if (discountArray.length > 0) {
            return discountArray[0];

        } else if (discountArray.length > 1) {
            console.log('discount table has multiple discounts with same id!');
            return discountArray[0];
        } else {
            return false
        }

    } catch (error) {
        console.log(error);
        return false;
    }
};

/**
 *
 * @param discount
 * @return {Promise<{discount: *}|boolean>}
 * object added to database or false if fails
 */
const addDiscount = async (discount) => {
    try {
        console.log('addDiscount in discount-model');

        //default discount values overridden by discount
        const newDiscount = {...default_discount, ...discount, message: "new discount added by discount-model"};

        //sql statement
        const sql =  `INSERT INTO discounts (discount, discount_code, date_start, date_end, message)
                              VALUES (?,?,?,?,?)`;
        console.log(sql);

        //sql parameters
        const params = [
            newDiscount.discount,
            newDiscount.discount_code,
            newDiscount.date_start,
            newDiscount.date_end,
            newDiscount.message
        ];
        console.log(params);

        //execute sql
        const rows = await promisePool.execute(sql, params);
        console.log('rows', rows);

        //return added discount
        if (rows[0].affectedRows === 0) {
            console.log('Discount not added');
            return false;

        } else {
            console.log('Discount added');
            return  findDiscountById(rows[0].insertId);
        }

    } catch (error) {
        console.log(error);
        return false;
    }
};


/**
 * Modifies a discount by id.
 *
 * @param discount discount object, only fields given will be updated
 * @param discountId number
 * @return {Promise<*|boolean>}
 * modified discount or false if error or not found
 */
const modifyDiscount = async (discount, discountId) => {
    try {
        console.log('modifyDiscount: ', discountId, discount);

        //get previous discount
        const previousDiscount = await findDiscountById(discountId);

        //abort if not found
        if (!previousDiscount) {
            return false;
        }

        //previous discount values overridden by new discount
        const updatedDiscount = {...previousDiscount, ...discount, message: "discount modified by discount-model"};

        //sql statement
        const sql = `UPDATE discounts SET discount = ?, discount_code = ?, date_start = ?, date_end = ?, message = ?
                     WHERE discounts.id = ?`;
        console.log(sql);

        //sql parameters
        const params = [
            updatedDiscount.discount,
            updatedDiscount.discount_code,
            updatedDiscount.date_start,
            updatedDiscount.date_end,
            updatedDiscount.message,
            discountId
        ];
        console.log(params);

        //execute sql
        const rows = await promisePool.execute(sql, params);
        console.log('rows', rows);

        //return modified discount of false if no affected rows
        if (rows[0].affectedRows !== 0) {
            console.log('return modified discount id: ',discountId);
            return findDiscountById(discountId);

        } else {
            console.log('Discount not modified');
            return false;
        }

    } catch (error) {
        console.log(error);
        return false;
    }
};

/**
 *
 * @param discountId number
 * @return {Promise<boolean>} false if not found
 */
const removeDiscount = async (discountId) => {
    try {
        // Prepare delete statement and execute
        const sql = "DELETE FROM discounts WHERE id = ?";
        const params = [discountId];
        const [rows] = await promisePool.execute(sql, params);
        // console.log("rows", rows);

        if (rows.affectedRows === 0) {
            console.log("Discount not found or not removed");
            return false;
        } else {
            console.log('discount removed');
            return true;
        }

    } catch (error) {
        console.log(error);
        return false;
    }

};



export {
    listAllDiscounts,
    findDiscountById,
    addDiscount,
    modifyDiscount,
    removeDiscount
};
