'use strict';

//bcrypt for passwords
import bcrypt from "bcrypt";
import promisePool from "../../utils/database.js";

//default datastructure
const default_giftCard = {
    id : 0,     //auto generated by backend
    value: 15.5,
    expiration_date : "2026-01-01",
    password: "giftcardpassword",
    message : "defauld giftcard, password is used to validate the giftcard",
    order: 0,   // foreign key to order.id
    user : 0,   // foreign key to user.id
}



/**
 *
 * @return
 * array of all objects or false if error
 */
const listAllGiftCards = async () => {
    try {
        console.log('listAllGiftCards in gift_card-model');
        const [gift_cardArray] = await promisePool.query('SELECT * FROM gift_cards');
        //console.log('gift_cardArray:', gift_cardArray);
        return gift_cardArray;

    } catch (error) {
        console.log('error in listAllGiftCards in gift_card-model');
        console.log(error);
        return false;
    }
};

/**
 * @param id
 * @return
 * first object that has the id or false if not found or error
 */
const findGiftCardById = async (id) => {
    try {
        console.log('findGiftCardById in gift_card-model');
        const query = promisePool.format('SELECT * FROM gift_cards where id = ?', id);
        const [gift_cardArray] = await promisePool.execute(query);


        if (gift_cardArray.length > 0) {
            return gift_cardArray[0];

        } else if (gift_cardArray.length > 1) {
            console.log('gift_card table has multiple gift_cards with same id!');
            return gift_cardArray[0];

        } else {
            return false
        }

    } catch (error) {
        console.log(error);
        return false;
    }
};

/**
 *
 * @param gift_card
 * @return
 * object added to database or false if fails
 *
 */
const addGiftCard = async (gift_card) => {
    try {
        console.log('addGiftCard in gift_card-model');

        //default gift_card values overridden by gift_card
        const newGiftCard = {...default_giftCard, ...gift_card, message: "new gift_card added by gift_card-model"};

        //sql statement
        const sql = `INSERT INTO gift_cards (value, expiration_date, password, message, gift_cards.order, user)
                      VALUES (?,?,?,?,?)`;
        console.log(sql);

        //sql parameters
        const params = [
            newGiftCard.value,
            newGiftCard.expiration_date,
            bcrypt.hashSync(newGiftCard.password,10),
            newGiftCard.message,
            newGiftCard.order,
            newGiftCard.user
        ];
        console.log(params);

        //execute sql
        const rows = await promisePool.execute(sql, params);
        console.log('rows', rows);

        //return added gift_card
        if (rows[0].affectedRows === 0) {
            console.log('gift_card not added');
            return false;

        } else {
            return findGiftCardById(rows[0].insertId);
        }

    } catch (error) {
        console.log(error);
        return false;
    }
};


/**
 *
 * @param giftCard gift_card object
 * @param giftCardId number
 * @return {Promise<*|boolean>}
 * gift_card or false if error or not found
 */
const modifyGiftCard = async (giftCard, giftCardId) => {
    try {
        console.log('modifyGiftCard in gift_card-model: ',giftCard, giftCardId);

        //get previous gift_card
        const previousGiftCard = await findGiftCardById(giftCardId);

        //abort if not found
        if (!previousGiftCard) {
            return false;
        }

        //default gift_card values overridden by gift_card
        const newGiftCard = {...previousGiftCard, ...giftCard, message: " gift_card modified by gift_card-model"};

        //sql statement
        const sql = `UPDATE gift_cards SET \`value\` = ?, \`expiration_date\` = ?, \`password\` = ?, message = ?, gift_cards.\`order\` = ?, \`user\` = ?
                      WHERE gift_cards.id = ?`;
        console.log(sql);

        //sql parameters
        const params = [
            newGiftCard.value,
            newGiftCard.expiration_date,
            bcrypt.hashSync(newGiftCard.password,10),
            newGiftCard.message,
            newGiftCard.order,
            newGiftCard.user,
            giftCardId
        ];
        console.log(params);

        //execute sql
        const rows = await promisePool.execute(sql, params);
        console.log('rows', rows);

        //return modified gift_card of false if no affected rows
        if (rows[0].affectedRows !== 0) {
            console.log('return modified user id: ',giftCardId);
            return findGiftCardById(giftCardId);

        } else {
            console.log('GiftCard not modified');
            return false;
        }

    } catch (error) {
        console.log(error);
        return false;
    }
};

/**
 *
 * @param giftCardId number
 * @return {Promise<boolean>} false if not found
 */
const removeGiftCard = async (giftCardId) => {
    try {

        // Prepare delete statement and execute
        const sql = "DELETE FROM gift_cards WHERE id = ?";
        const params = [giftCardId];
        const [rows] = await promisePool.execute(sql, params);
        // console.log("rows", rows);

        if (rows.affectedRows === 0) {
            console.log("GiftCard not found or not removed");
            return false;
        }

        return true;

    } catch (error) {
        console.log(error);
        return false;
    }

};

/**
 *
 * @param userId
 * @return {Promise<*|boolean|*[]>}
 * array of gift_cards filtered by given id. Can return empty array. Returns false if error.
 */
const findGiftCardsByUserId = async (userId) => {
    try {
        console.log('findGiftCardByUserId in gift_card-model: ', userId);
        const query = promisePool.format('SELECT * FROM gift_cards where gift_cards.user = ?', userId);
        const [giftCardArray] = await promisePool.execute(query);

        if (giftCardArray.length > 0) {
            return giftCardArray;

        } else {
            return [];
        }

    } catch (error) {
        console.log(error);
        return false;
    }
}


/**
 * @return
 * array filtered by id given or false if error
 * @param orderId
 */
const findGiftCardsByOrder = async (orderId) => {
    try {
        console.log('findGiftCardsByOrder in gift_card-model:', orderId);
        const query = promisePool.format('SELECT * FROM gift_cards where gift_cards.order = ?', orderId);
        const [gift_cardArray] = await promisePool.execute(query);

        if (gift_cardArray.length > 0) {
            return gift_cardArray;

        } else {
            return [];
        }

    } catch (error) {
        console.log(error);
        return false;
    }
}



export {
    listAllGiftCards,
    findGiftCardById,
    addGiftCard,
    modifyGiftCard,
    removeGiftCard,
    findGiftCardsByUserId,
    findGiftCardsByOrder
}