'use strict';

//imports
import promisePool from "../../utils/database.js";

//default datastructure
const default_reservation = {
    id : 0,     //auto generated by backend
    user: 1,    //vieras avain
    order : 1,  //Vieras avain
    date : "2025-12-06 12:00:00",
    table_customer_count : 1,   //Grillivaraus - henkilöiden määrä
    grill_customer_count : 2,   //Pöytävaraus - henkilöiden määrä
    message : 'default reservation',
}



/**
 *
 * @return
 * array of all objects or false if error
 */
const listAllReservations = async () => {
    try {
        console.log('listAllReservations in reservation-model');
        const [reservationArray] = await promisePool.query('SELECT * FROM reservations');
        //console.log('reservationArray:', reservationArray);
        return reservationArray;

    } catch (error) {
        console.log('error in listAllReservations in reservation-model');
        console.log(error);
        return false;
    }
};

/**
 * @param id
 * @return
 * first object that has the id or false if not found or error
 */
const findReservationById = async (id) => {
    try {
        console.log('findReservationById in reservation-model');
        const query = promisePool.format('SELECT * FROM reservations where id = ?', id);
        const [reservationArray] = await promisePool.execute(query);


        if (reservationArray.length > 0) {
            return reservationArray[0];

        } else if (reservationArray.length > 1) {
            console.log('reservation table has multiple reservations with same id!');
            return reservationArray[0];
        } else {
            return false
        }

    } catch (error) {
        console.log(error);
        return false;
    }
};

/**
 *
 * @param reservation
 * @return
 * object added to database or false if fails
 *
 */
const addReservation = async (reservation) => {
    try {
        console.log('addReservation in reservation-model');

        //default reservation values overridden by reservation
        const newReservation = {...default_reservation, ...reservation, message: "new reservation added by reservation-model"};

        //sql statement
        const sql = `INSERT INTO reservations (user, \`order\`, date, table_customer_count, grill_customer_count, message)
                      VALUES (?,?,?,?,?,?)`;
        console.log(sql);

        //sql parameters
        const params = [
            newReservation.user,
            newReservation.order,
            newReservation.date,
            newReservation.table_customer_count,
            newReservation.grill_customer_count,
            newReservation.message
        ];
        console.log(params);

        //execute sql
        const rows = await promisePool.execute(sql, params);
        console.log('rows', rows);

        //return added reservation
        if (rows[0].affectedRows === 0) {
            console.log('reservation not added');
            return false;

        } else {
            return findReservationById(rows[0].insertId);
        }

    } catch (error) {
        console.log(error);
        return false;
    }
};


/**
 *
 * @param reservation reservation object
 * @param reservationId number
 * @return {Promise<*|boolean>}
 * reservation or false if error or not found
 */
const modifyReservation = async (reservation, reservationId) => {
    try {
        console.log('modifyReservation in reservation-model: ',reservation, reservationId);

        //get previous reservation
        const previousReservation = await findReservationById(reservationId);

        //abort if not found
        if (!previousReservation) {
            return false;
        }

        //default reservation values overridden by reservation
        const newReservation = {...previousReservation, ...reservation, message: " reservation modified by reservation-model"};

        //sql statement
        const sql = `UPDATE reservations SET user = ?, \`order\` = ?, date = ?, table_customer_count = ?, grill_customer_count = ?, message = ?
                      WHERE reservations.id = ?`;
        console.log(sql);

        //sql parameters
        const params = [
            newReservation.user,
            newReservation.order,
            newReservation.date,
            newReservation.table_customer_count,
            newReservation.grill_customer_count,
            newReservation.message,
            reservationId
        ];
        console.log(params);

        //execute sql
        const rows = await promisePool.execute(sql, params);
        console.log('rows', rows);

        //return modified reservation of false if no affected rows
        if (rows[0].affectedRows !== 0) {
            console.log('return modified user id: ',reservationId);
            return findReservationById(reservationId);

        } else {
            console.log('Reservation not modified');
            return false;
        }

    } catch (error) {
        console.log(error);
        return false;
    }
};

/**
 *
 * @param reservationId number
 * @return {Promise<boolean>} false if not found
 */
const removeReservation = async (reservationId) => {
    try {

        // Prepare delete statement and execute
        const sql = "DELETE FROM reservations WHERE id = ?";
        const params = [reservationId];
        const [rows] = await promisePool.execute(sql, params);
        // console.log("rows", rows);

        if (rows.affectedRows === 0) {
            console.log("Reservation not found or not removed");
            return false;
        }

        return true;

    } catch (error) {
        console.log(error);
        return false;
    }

};

/**
 *
 * @param userId
 * @return {Promise<*|boolean|*[]>}
 * array of reservations filtered by given id. Can return empty array. Returns false if error.
 */
const findReservationsByUserId = async (userId) => {
    try {
        console.log('findReservationByUserId in reservation-model: ', userId);
        const query = promisePool.format('SELECT * FROM reservations where reservations.user = ?', userId);
        const [reservationArray] = await promisePool.execute(query);

        if (reservationArray.length > 0) {
            return reservationArray;

        } else {
            return [];
        }

    } catch (error) {
        console.log(error);
        return false;
    }
}


/**
 * @param orderId
 * @return
 * array of reservations filtered by given id. Can return empty array. Returns false if error.
 */
const findReservationsByOrder = async (orderId) => {
    try {
        console.log('findReservationsByOrder in reservation-model: ',orderId);
        const query = promisePool.format('SELECT * FROM reservations where reservations.order = ?', orderId);
        const [reservationArray] = await promisePool.execute(query);

        if (reservationArray.length > 0) {
            return reservationArray;

        } else {
            return [];
        }

    } catch (error) {
        console.log(error);
        return false;
    }
}

/**
 * @param date
 * @return
 * array filtered by id given or false if error
 */
const findReservationsByDate = async (date) => {
    try {
        console.log('findReservationsByDate in reservation-model:', date);
        const query = promisePool.format('SELECT * FROM reservations where reservations.date = ?', date);
        const [reservationArray] = await promisePool.execute(query);

        if (reservationArray.length > 0) {
            return reservationArray;

        } else {
            return [];
        }

    } catch (error) {
        console.log(error);
        return false;
    }
}

export {
    listAllReservations,
    findReservationById,
    addReservation,
    modifyReservation,
    removeReservation,
    findReservationsByUserId,
    findReservationsByOrder,
    findReservationsByDate
};
