-- MySQL Script generated by MySQL Workbench
-- Mon Nov 24 12:12:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wsk_restaurant_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Drop and create database wsk_restaurant
-- -----------------------------------------------------

DROP DATABASE IF EXISTS wsk_restaurant;
CREATE DATABASE wsk_restaurant;
USE wsk_restaurant;

-- -----------------------------------------------------
-- Create user and grant privileges
-- -----------------------------------------------------

DROP USER IF EXISTS appuser@localhost;
CREATE USER appuser@localhost IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON wsk_restaurant.* TO appuser@localhost;
FLUSH PRIVILEGES;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  `role` VARCHAR(45) NOT NULL DEFAULT 'user',
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `picture` VARCHAR(100) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `meals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meals` ;

CREATE TABLE IF NOT EXISTS `meals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_fi` VARCHAR(50) NULL,
  `name_en` VARCHAR(50) NULL,
  `description_fi` VARCHAR(200) NULL,
  `description_en` VARCHAR(200) NULL,
  `cost` FLOAT NULL,
  `picture` VARCHAR(100) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `locations` ;

CREATE TABLE IF NOT EXISTS `locations` (
  `id` INT NOT NULL,
  `address` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `phone` VARCHAR(100) NULL,
  `table_count` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orders` ;

CREATE TABLE IF NOT EXISTS `orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `cost_total` FLOAT NULL DEFAULT NULL,
  `timestamp` TIMESTAMP NULL,
  `location` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_id_in_orders`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`),
  CONSTRAINT `target_location_in_orders`
    FOREIGN KEY (`location`)
    REFERENCES `locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `user_id_in_orders` ON `orders` (`user_id` ASC) VISIBLE;

CREATE INDEX `target_location_in_orders_idx` ON `orders` (`location` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gift_cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gift_cards` ;

CREATE TABLE IF NOT EXISTS `gift_cards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `expiration_date` DATE NULL,
  `password` VARCHAR(50) NULL,
  `value` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lunch_reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lunch_reservations` ;

CREATE TABLE IF NOT EXISTS `lunch_reservations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `location` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `target_location_LR`
    FOREIGN KEY (`location`)
    REFERENCES `locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `target_location_LR_idx` ON `lunch_reservations` (`location` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `order_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `order_items` ;

CREATE TABLE IF NOT EXISTS `order_items` (
  `order_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `amount` INT NOT NULL,
  `meal_id` INT NULL,
  `gift_card_id` INT NULL,
  `lunch_reservation_id` INT NULL,
  CONSTRAINT `order_id_OI`
    FOREIGN KEY (`order_id`)
    REFERENCES `orders` (`id`),
  CONSTRAINT `meal_id_OI`
    FOREIGN KEY (`meal_id`)
    REFERENCES `meals` (`id`),
  CONSTRAINT `gift_card_id_OI`
    FOREIGN KEY (`gift_card_id`)
    REFERENCES `gift_cards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lunch_reservation_id_OI`
    FOREIGN KEY (`lunch_reservation_id`)
    REFERENCES `lunch_reservations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `order_id_OI` ON `order_items` (`order_id` ASC) VISIBLE;

CREATE INDEX `meal_id_OI` ON `order_items` (`meal_id` ASC) VISIBLE;

CREATE INDEX `gift_card_id_idx` ON `order_items` (`gift_card_id` ASC) VISIBLE;

CREATE INDEX `lunch_reservation_id_idx` ON `order_items` (`lunch_reservation_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `daily_menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daily_menus` ;

CREATE TABLE IF NOT EXISTS `daily_menus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL DEFAULT NULL,
  `picture` VARCHAR(100) NULL,
  `location` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `target_location_id`
    FOREIGN KEY (`location`)
    REFERENCES `locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `DM_location_id_idx` ON `daily_menus` (`location` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `daily_menu_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daily_menu_items` ;

CREATE TABLE IF NOT EXISTS `daily_menu_items` (
  `daily_menu_id` INT NOT NULL,
  `meal_id` INT NOT NULL,
  CONSTRAINT `daily_menu_id_DMI`
    FOREIGN KEY (`daily_menu_id`)
    REFERENCES `daily_menus` (`id`),
  CONSTRAINT `meal_id_DMI`
    FOREIGN KEY (`meal_id`)
    REFERENCES `meals` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE INDEX `daily_menu_id_DMI` ON `daily_menu_items` (`daily_menu_id` ASC) VISIBLE;

CREATE INDEX `meal_id_idx` ON `daily_menu_items` (`meal_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `discounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discounts` ;

CREATE TABLE IF NOT EXISTS `discounts` (
  `id` INT NOT NULL,
  `discount_code` VARCHAR(45) NULL,
  `date_start` DATE NULL,
  `date_end` VARCHAR(45) NULL,
  `target_meal` INT NULL,
  `cost_override` FLOAT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `target_meal_in_discounts`
    FOREIGN KEY (`target_meal`)
    REFERENCES `meals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `target_meal_idx` ON `discounts` (`target_meal` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
