### get discounts
GET http://localhost:3000/api/discounts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDUzNDMwOCwiZXhwIjoxNzY0NjIwNzA4fQ.A8AJrtPJgFjf2f7wumLD21_tSbD73ZfBpyIHWVUvpEI

### post new discount
POST http://localhost:3000/api/discounts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDY2NzU2NSwiZXhwIjoxNzY0NzUzOTY1fQ.V42nZ5P0krG60ohNoqlaBkn9f-xjcOgcjO1A1i7NXSc

{
  "id" : 5,
  "target_meal": 1,
  "cost_override": 6.9,
  "discount_code" : "just in case getting the discount needs a code",
  "date_start": "some start date",
  "date_end": "some end date",
  "message": "cost_override is the discounted cost"
}

### get discount by id
GET http://localhost:3000/api/discounts/3

### update discount by id
PUT http://localhost:3000/api/discounts/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDU4NTY4MiwiZXhwIjoxNzY0NjcyMDgyfQ.Od8qbnjDXH13TS1CN6DVzOru8AR1DL0Q7gY1kFgo_1U

{
  "id" : 3,
  "target_meal": 6,
  "cost_override": 6.9,
  "discount_code" : "just in case getting the discount needs a code",
  "date_start": "some start date",
  "date_end": "some end date",
  "message": "cost_override is the discounted cost"
}

### delete discount by id
DELETE http://localhost:3000/api/discounts/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDY2NzU2NSwiZXhwIjoxNzY0NzUzOTY1fQ.V42nZ5P0krG60ohNoqlaBkn9f-xjcOgcjO1A1i7NXSc

### gen an array of discounts by sending an array of ids
## returns false for ids not found
POST http://localhost:3000/api/discounts/list/id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Im5hbWUiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBlbWFpbC5maSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTE3NDkzNiwiZXhwIjoxNzY1MjYxMzM2fQ.54PX88Tt0p54w2cjN-2Y6HslSKpqcoRcFG4iPoPVaUw

{
  "discounts" : [3, 2, 0]
}