### get discounts
GET http://localhost:3000/api/discounts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDUzNDMwOCwiZXhwIjoxNzY0NjIwNzA4fQ.A8AJrtPJgFjf2f7wumLD21_tSbD73ZfBpyIHWVUvpEI

### post new discount
POST http://localhost:3000/api/discounts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDU4NTY4MiwiZXhwIjoxNzY0NjcyMDgyfQ.Od8qbnjDXH13TS1CN6DVzOru8AR1DL0Q7gY1kFgo_1U

{
  "id" : 4,
  "target_meal": 1,
  "cost_override": 6.9,
  "discount_code" : "just in case getting the discount needs a code",
  "date_start": "some start date",
  "date_end": "some end date",
  "message": "cost_override is the discounted cost"
}

### get discount by id
GET http://localhost:3000/api/discounts/3

### update discount by id
PUT http://localhost:3000/api/discounts/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDU4NTY4MiwiZXhwIjoxNzY0NjcyMDgyfQ.Od8qbnjDXH13TS1CN6DVzOru8AR1DL0Q7gY1kFgo_1U

{
  "id" : 3,
  "target_meal": 6,
  "cost_override": 6.9,
  "discount_code" : "just in case getting the discount needs a code",
  "date_start": "some start date",
  "date_end": "some end date",
  "message": "cost_override is the discounted cost"
}

### delete discount by id
DELETE http://localhost:3000/api/discounts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDU4NTY4MiwiZXhwIjoxNzY0NjcyMDgyfQ.Od8qbnjDXH13TS1CN6DVzOru8AR1DL0Q7gY1kFgo_1U

### get discount by meal id
GET http://localhost:3000/api/discounts/bymeal/700
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDU4NTY4MiwiZXhwIjoxNzY0NjcyMDgyfQ.Od8qbnjDXH13TS1CN6DVzOru8AR1DL0Q7gY1kFgo_1U

