### get giftcards
GET http://localhost:3000/api/giftcards/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDc3Mjg1NywiZXhwIjoxNzY0ODU5MjU3fQ.h7LtGVPqcww9nCvEjnYSGVm_QjR-0ZLZzH5Nn4L76Bs

### post new giftcards
POST http://localhost:3000/api/giftcards/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDc3Mjg1NywiZXhwIjoxNzY0ODU5MjU3fQ.h7LtGVPqcww9nCvEjnYSGVm_QjR-0ZLZzH5Nn4L76Bs

{
  "id" : 0,
  "value": 15.5,
  "expiration_date" : "20260101",
  "password": "giftcardpassword",
  "redeemed": false,
  "message" : "defauld giftcard, password is used to validate the giftcard, redeemed: boolean indicates if card has been redeemed",
  "order": 0,
  "user" : 0
}

### get giftcard by id
GET http://localhost:3000/api/giftcards/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDc3Mjg1NywiZXhwIjoxNzY0ODU5MjU3fQ.h7LtGVPqcww9nCvEjnYSGVm_QjR-0ZLZzH5Nn4L76Bs


### update giftcard by id
PUT http://localhost:3000/api/giftcards/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDc3Mjg1NywiZXhwIjoxNzY0ODU5MjU3fQ.h7LtGVPqcww9nCvEjnYSGVm_QjR-0ZLZzH5Nn4L76Bs

{
  "id" : 0,
  "value": 15.5,
  "expiration_date" : "20260101",
  "password": "giftcardpassword",
  "redeemed": true,
  "message" : "defauld giftcard, password is used to validate the giftcard, redeemed: boolean indicates if card has been redeemed",
  "order": 0,
  "user" : 0
}

### delete giftcard by id
DELETE http://localhost:3000/api/giftcards/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDc3Mjg1NywiZXhwIjoxNzY0ODU5MjU3fQ.h7LtGVPqcww9nCvEjnYSGVm_QjR-0ZLZzH5Nn4L76Bs

### get giftcard by user id
GET http://localhost:3000/api/giftcards/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDc3Mjg1NywiZXhwIjoxNzY0ODU5MjU3fQ.h7LtGVPqcww9nCvEjnYSGVm_QjR-0ZLZzH5Nn4L76Bs

### validate that giftcard is real and not redeemed by password
GET http://localhost:3000/api/giftcards/validate/password3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDc3Mjg1NywiZXhwIjoxNzY0ODU5MjU3fQ.h7LtGVPqcww9nCvEjnYSGVm_QjR-0ZLZzH5Nn4L76Bs

### redeem a giftcard by password
PUT http://localhost:3000/api/giftcards/redeem/password1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDc3Mjg1NywiZXhwIjoxNzY0ODU5MjU3fQ.h7LtGVPqcww9nCvEjnYSGVm_QjR-0ZLZzH5Nn4L76Bs
