### get locations
GET http://localhost:3000/api/locations/

### post new location
POST http://localhost:3000/api/locations/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDY3NTczMCwiZXhwIjoxNzY0NzYyMTMwfQ.2p2F5XQC4ZhcbjpvhIqcyPzy_RVam4YIb113XTWVe3Q

{
  "id" : 5,
  "name" : "name",
  "address" : "",
  "email" : "",
  "phone" : "",
  "table_count" : 10,
  "message" : "new location"
}

### get location by id
GET http://localhost:3000/api/locations/5

### update location by id
PUT http://localhost:3000/api/locations/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDY3NTczMCwiZXhwIjoxNzY0NzYyMTMwfQ.2p2F5XQC4ZhcbjpvhIqcyPzy_RVam4YIb113XTWVe3Q

{
  "id" : 1,
  "name" : "name",
  "address" : "",
  "email" : "",
  "phone" : "",
  "table_count" : 10,
  "message" : "updated location"
}

### delete location by id
DELETE http://localhost:3000/api/locations/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDY3NTczMCwiZXhwIjoxNzY0NzYyMTMwfQ.2p2F5XQC4ZhcbjpvhIqcyPzy_RVam4YIb113XTWVe3Q
