### get meals
GET http://localhost:3000/api/meals/

### post new meal WITHOUT picture
## see tests/upload-form.html how to upload with image
POST http://localhost:3000/api/meals/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDU5NzQ4MSwiZXhwIjoxNzY0NjgzODgxfQ.FNpsX4Dhp6w5i2nYWzQ4KWHysf0h4qlTVkxbhBrH2u4

{
  "id" : 234,
  "name_fi": "suomenkielinen nimi",
  "name_en": "english name",
  "description_fi": "suomalainen kuvaus tuotteelle",
  "description_en": "english description for the item",
  "cost": 0.0,
  "type": "noudettava annos/ pöytävaraus / lahjakortti ?",
  "image": "public/images/burger.jpg"
}

### get meal by id
GET http://localhost:3000/api/meals/2

### update meal by id
PUT http://localhost:3000/api/meals/234
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDU5NzQ4MSwiZXhwIjoxNzY0NjgzODgxfQ.FNpsX4Dhp6w5i2nYWzQ4KWHysf0h4qlTVkxbhBrH2u4

{
  "id" : 0,
  "name_fi": "suomenkielinen nimi",
  "name_en": "english name",
  "description_fi": "suomalainen kuvaus tuotteelle",
  "description_en": "english description for the item",
  "cost": 0.0,
  "type": "noudettava annos/ pöytävaraus / lahjakortti ?",
  "image": "public/images/burger.jpg"
}

### delete meal by id
DELETE http://localhost:3000/api/meals/54
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDU5NzQ4MSwiZXhwIjoxNzY0NjgzODgxfQ.FNpsX4Dhp6w5i2nYWzQ4KWHysf0h4qlTVkxbhBrH2u4


### meal upload WITH picture (formadata  HTTP/1.1 )
POST http://localhost:3000/api/meals/
Content-Type: multipart/form-data; boundary=MyBoundary
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImRlZmF1bHQiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJkZWZhdWx0Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY0OTM0ODIzLCJleHAiOjE3NjUwMjEyMjN9.easmf4SlV-0hKRkF-zlEWYtmJKu-oRMuWQVJt7pq_Ik

--MyBoundary
Content-Disposition: form-data; name="id"

54
--MyBoundary
Content-Disposition: form-data; name="name_fi"

suomenkielinen nimi
--MyBoundary
Content-Disposition: form-data; name="name_en"

english name
--MyBoundary
Content-Disposition: form-data; name="description_fi"

description_fi
--MyBoundary
Content-Disposition: form-data; name="description_en"

description_en
--MyBoundary
Content-Disposition: form-data; name="cost"

40
--MyBoundary
Content-Disposition: form-data; name="type"

"food?"
--MyBoundary
Content-Disposition: form-data; name="file"; filename="lautanen.jpg"
Content-Type: image/jpg

< ./lautanen.jpg
--MyBoundary--
