### get orders
#only for admin users
GET http://localhost:3000/api/orders/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJyb2xlIiwiaWF0IjoxNzYzNTUzOTA4LCJleHAiOjE3NjM2NDAzMDh9.byQigsIuCBQ69kHu1VkgoRAgC9HY0mZigw1Gps5xQTw

### get order by id
#use login with default user first, then copy token here
GET http://localhost:3000/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJyb2xlIiwiaWF0IjoxNzYzNTUzOTA4LCJleHAiOjE3NjM2NDAzMDh9.byQigsIuCBQ69kHu1VkgoRAgC9HY0mZigw1Gps5xQTw