### get orders
#only for admin users
GET http://localhost:3000/api/orders/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDY2NjQ3OSwiZXhwIjoxNzY0NzUyODc5fQ.4UA-oa-6DBO53g1nSpbmX87HGQeCsxlISCbgocO-cXE

###post new order
POST http://localhost:3000/api/orders/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDY2NjQ3OSwiZXhwIjoxNzY0NzUyODc5fQ.4UA-oa-6DBO53g1nSpbmX87HGQeCsxlISCbgocO-cXE

{
  "id" : 0,
  "user": 0,
  "cost": 10.5,
  "timestamp": "2025-12-06 12:00:00",
  "reservations" : [ 1, 2, 3 ],
  "gift_cards": [ 1 ],
  "message": "reservations = array of reservation id, gift_cards = array of card id"
}


### get order by id
#use login with default user first, then copy token here
GET http://localhost:3000/api/orders/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDY2NjQ3OSwiZXhwIjoxNzY0NzUyODc5fQ.4UA-oa-6DBO53g1nSpbmX87HGQeCsxlISCbgocO-cXE

### update order by id
PUT http://localhost:3000/api/orders/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDY2NjQ3OSwiZXhwIjoxNzY0NzUyODc5fQ.4UA-oa-6DBO53g1nSpbmX87HGQeCsxlISCbgocO-cXE

{
  "id" : 0,
  "user": 0,
  "cost": 10.5,
  "timestamp": "2025-12-06 12:00:00",
  "reservations" : [ 1, 2, 3 ],
  "gift_cards": [ 1 ],
  "message": "reservations = array of reservation id, gift_cards = array of card id"
}

### delete order by id
DELETE http://localhost:3000/api/orders/75
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDY2NjQ3OSwiZXhwIjoxNzY0NzUyODc5fQ.4UA-oa-6DBO53g1nSpbmX87HGQeCsxlISCbgocO-cXE

### get orders by user id
GET http://localhost:3000/api/orders/user/15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDY2NjQ3OSwiZXhwIjoxNzY0NzUyODc5fQ.4UA-oa-6DBO53g1nSpbmX87HGQeCsxlISCbgocO-cXE

### get order by location id
GET http://localhost:3000/api/orders/location/0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDY2NjQ3OSwiZXhwIjoxNzY0NzUyODc5fQ.4UA-oa-6DBO53g1nSpbmX87HGQeCsxlISCbgocO-cXE

### get order by date
GET http://localhost:3000/api/orders/date/20251202
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDY2NjQ3OSwiZXhwIjoxNzY0NzUyODc5fQ.4UA-oa-6DBO53g1nSpbmX87HGQeCsxlISCbgocO-cXE


