### login with default user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "password"
}

### login with default admin user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

### get validate current token
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJyb2xlIiwiaWF0IjoxNzY0MjMxNTE0LCJleHAiOjE3NjQzMTc5MTR9.HQ76_unLvvLlK9Dz9lf41rwKFJ8NTU_0OE5ebZ2t4-8

### get orders
#only for admin users
GET http://localhost:3000/api/orders/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJyb2xlIiwiaWF0IjoxNzYzNTUzOTA4LCJleHAiOjE3NjM2NDAzMDh9.byQigsIuCBQ69kHu1VkgoRAgC9HY0mZigw1Gps5xQTw

### get order by id
#use login with default user first, then copy token here
GET http://localhost:3000/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJyb2xlIiwiaWF0IjoxNzYzNTUzOTA4LCJleHAiOjE3NjM2NDAzMDh9.byQigsIuCBQ69kHu1VkgoRAgC9HY0mZigw1Gps5xQTw