### get meals
GET http://localhost:3000/api/meals/

### get meals from server
GET https://wsk-restaurant-server.norwayeast.cloudapp.azure.com/api/meals/


### post new meal WITHOUT picture
## see tests/upload-form.html how to upload with image
POST http://localhost:3000/api/meals/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDU5NzQ4MSwiZXhwIjoxNzY0NjgzODgxfQ.FNpsX4Dhp6w5i2nYWzQ4KWHysf0h4qlTVkxbhBrH2u4

{
  "id" : 234,
  "name_fi": "suomenkielinen nimi",
  "name_en": "english name",
  "description_fi": "suomalainen kuvaus tuotteelle",
  "description_en": "english description for the item",
  "cost": 0.0,
  "type": "noudettava annos/ pöytävaraus / lahjakortti ?",
  "image": "public/images/burger.jpg"
}

### get meal by id
GET http://localhost:3000/api/meals/1

### update meal by id
PUT http://localhost:3000/api/meals/234
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDU5NzQ4MSwiZXhwIjoxNzY0NjgzODgxfQ.FNpsX4Dhp6w5i2nYWzQ4KWHysf0h4qlTVkxbhBrH2u4

{
  "id" : 0,
  "name_fi": "suomenkielinen nimi",
  "name_en": "english name",
  "description_fi": "suomalainen kuvaus tuotteelle",
  "description_en": "english description for the item",
  "cost": 0.0,
  "type": "noudettava annos/ pöytävaraus / lahjakortti ?",
  "image": "public/images/burger.jpg"
}

### delete meal by id
DELETE http://localhost:3000/api/meals/54
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDU5NzQ4MSwiZXhwIjoxNzY0NjgzODgxfQ.FNpsX4Dhp6w5i2nYWzQ4KWHysf0h4qlTVkxbhBrH2u4


### gen an array of meals by sending an array of ids
## returns false for ids not found
POST http://localhost:3000/api/meals/list/id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Im5hbWUiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBlbWFpbC5maSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTE3NDkzNiwiZXhwIjoxNzY1MjYxMzM2fQ.54PX88Tt0p54w2cjN-2Y6HslSKpqcoRcFG4iPoPVaUw

{
  "meals" : [3, 2, 0]
}



### meal upload WITH picture (formadata  HTTP/1.1 )
POST http://localhost:3000/api/meals/
Content-Type: multipart/form-data; boundary=MyBoundary
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Im5hbWUiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBlbWFpbC5maSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTIzMjgzNCwiZXhwIjoxNzY1MzE5MjM0fQ.jPc5eVacv1mKXETe9lOkPTujGx03mNsisRgd5YuaD5U

--MyBoundary
Content-Disposition: form-data; name="id"

54
--MyBoundary
Content-Disposition: form-data; name="name_fi"

suomenkielinen nimi
--MyBoundary
Content-Disposition: form-data; name="name_en"

english name
--MyBoundary
Content-Disposition: form-data; name="description_fi"

description_fi
--MyBoundary
Content-Disposition: form-data; name="description_en"

description_en
--MyBoundary
Content-Disposition: form-data; name="cost"

40
--MyBoundary
Content-Disposition: form-data; name="type"

"food?"
--MyBoundary
Content-Disposition: form-data; name="file"; filename="lautanen.jpg"
Content-Type: image/jpg

< ./lautanen.jpg
--MyBoundary--


### update meal with picture
PUT http://localhost:3000/api/meals/24
Content-Type: multipart/form-data; boundary=MyBoundary
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Im5hbWUiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBlbWFpbC5maSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTIzMjgzNCwiZXhwIjoxNzY1MzE5MjM0fQ.jPc5eVacv1mKXETe9lOkPTujGx03mNsisRgd5YuaD5U

--MyBoundary
Content-Disposition: form-data; name="id"

24
--MyBoundary
Content-Disposition: form-data; name="name_fi"

suomenkielinen nimi
--MyBoundary
Content-Disposition: form-data; name="name_en"

english name
--MyBoundary
Content-Disposition: form-data; name="description_fi"

description_fi
--MyBoundary
Content-Disposition: form-data; name="description_en"

description_en
--MyBoundary
Content-Disposition: form-data; name="cost"

40
--MyBoundary
Content-Disposition: form-data; name="type"

"food?"
--MyBoundary
Content-Disposition: form-data; name="file"; filename="burger.jpg"
Content-Type: image/jpg

< ./burger.jpg
--MyBoundary--


