-- MySQL Script generated by MySQL Workbench
-- Mon Dec  8 02:49:24 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wsk_restaurant_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Drop and create database wsk_restaurant
-- -----------------------------------------------------

DROP DATABASE IF EXISTS wsk_restaurant;
CREATE DATABASE wsk_restaurant;
USE wsk_restaurant;

-- -----------------------------------------------------
-- Create user and grant privileges
-- -----------------------------------------------------

DROP USER IF EXISTS appuser@localhost;
CREATE USER appuser@localhost IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON wsk_restaurant.* TO appuser@localhost;
FLUSH PRIVILEGES;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `role` VARCHAR(50) NULL,
  `name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `image` VARCHAR(100) NULL,
  `message` TEXT NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `meals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meals` ;

CREATE TABLE IF NOT EXISTS `meals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_fi` VARCHAR(100) NULL,
  `name_en` VARCHAR(100) NULL,
  `description_fi` TEXT NULL,
  `cost` FLOAT NULL,
  `type` VARCHAR(50) NULL,
  `description_en` TEXT NULL,
  `image` VARCHAR(100) NULL,
  `message` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orders` ;

CREATE TABLE IF NOT EXISTS `orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` INT NULL DEFAULT NULL,
  `cost` FLOAT NULL DEFAULT NULL,
  `timestamp` DATETIME NULL,
  `message` MEDIUMTEXT NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`));

CREATE INDEX `user_id_in_orders` ON `orders` (`user` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `menus` ;

CREATE TABLE IF NOT EXISTS `menus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `week` INT NULL,
  `special_meal` INT NULL,
  `image` VARCHAR(100) NULL,
  `message` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `menu_meals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `menu_meals` ;

CREATE TABLE IF NOT EXISTS `menu_meals` (
  `menu` INT NOT NULL,
  `meal` INT NOT NULL);

CREATE INDEX `menu_id_in_DMI` ON `menu_meals` (`menu` ASC) VISIBLE;

CREATE INDEX `meal_id_idx` ON `menu_meals` (`meal` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gift_cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gift_cards` ;

CREATE TABLE IF NOT EXISTS `gift_cards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` FLOAT NULL,
  `expiration_date` DATE NULL,
  `password` VARCHAR(100) NULL,
  `message` MEDIUMTEXT NULL,
  `order` INT NULL,
  `user` INT NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `user_in_gift_cards_idx` ON `gift_cards` (`user` ASC) VISIBLE;

CREATE INDEX `order_in_gift_cards_idx` ON `gift_cards` (`order` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservations` ;

CREATE TABLE IF NOT EXISTS `reservations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` INT NULL,
  `order` INT NULL,
  `date` DATETIME NULL,
  `table_customer_count` INT NULL,
  `grill_customer_count` INT NULL,
  `message` MEDIUMTEXT NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `user_in_LR_idx` ON `reservations` (`user` ASC) VISIBLE;

CREATE INDEX `order_in_LR_idx` ON `reservations` (`order` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `discounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discounts` ;

CREATE TABLE IF NOT EXISTS `discounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `discount` FLOAT NULL,
  `discount_code` VARCHAR(100) NULL,
  `date_start` DATE NULL,
  `date_end` DATE NULL,
  `message` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `locations` ;

CREATE TABLE IF NOT EXISTS `locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `address` VARCHAR(200) NULL,
  `email` VARCHAR(100) NULL,
  `phone` VARCHAR(100) NULL,
  `table_count` INT NULL,
  `message` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `order_reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `order_reservations` ;

CREATE TABLE IF NOT EXISTS `order_reservations` (
  `order` INT NULL,
  `reservation` INT NULL)
ENGINE = InnoDB;

CREATE INDEX `order_id_in_OrRe_idx` ON `order_reservations` (`order` ASC) VISIBLE;

CREATE INDEX `reservation_id_in_OrRe_idx` ON `order_reservations` (`reservation` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `order_gift_cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `order_gift_cards` ;

CREATE TABLE IF NOT EXISTS `order_gift_cards` (
  `order` INT NOT NULL,
  `gift_card` INT NOT NULL)
ENGINE = InnoDB;

CREATE INDEX `order_id_in_ORGC_idx` ON `order_gift_cards` (`order` ASC) VISIBLE;

CREATE INDEX `gift_card_id_in_ORGC_idx` ON `order_gift_cards` (`gift_card` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- insert-mock-data.sql
-- Mock data for wsk_restaurant_schema

-- insert-mock-data.sql
-- Mock data for wsk_restaurant_schema

-- -----------------------
-- Table `users`
-- -----------------------
INSERT INTO `users` (username, `password`, `role`, `name`, `email`, `image`, message) VALUES
('admin','$2b$10$SwiO2GYHWj1WzebSL3taJ.dXiXs5rN9mWz6Tk6PgGnhUopGk8Dhv6', 'admin', 'name', 'admin@email.fi', 'placeholder.jpg','mock data from database'),
('username','$2b$10$sJ//y1vPPH21XJCGpKDKvuDRx.LFM9b6R02DetaPmzRZQzKUw07y.', 'user', 'Bob Smith', 'bob@example.com', 'placeholder.jpg','mock data from database'),
('username3','pass789', 'user', 'Charlie Brown', 'charlie@example.com', NULL,'mock data from database'),
('username4','pass101', 'user', 'David Lee', 'david@example.com', 'david.jpg','mock data from database'),
('username5','pass102', 'user', 'Eva Green', 'eva@example.com', 'eva.jpg','mock data from database'),
('username6','pass103', 'admin', 'Frank White', 'frank@example.com', NULL,'mock data from database'),
('username7','pass104', 'user', 'Grace Kim', 'grace@example.com', 'grace.jpg','mock data from database'),
('username8','pass105', 'user', 'Henry Tan', 'henry@example.com', NULL,'mock data from database'),
('username9','pass106', 'user', 'Ivy Chen', 'ivy@example.com', 'ivy.jpg','mock data from database'),
('username10','pass107', 'user', 'Jack Liu', 'jack@example.com', NULL,'mock data from database');

-- -----------------------
-- Table `locations`
-- -----------------------
INSERT INTO `locations` (`id`,`name`, `address`, `email`, `phone`, `table_count`, `message`) VALUES
(1, 'Restauranto', '123 Main St, Helsinki', 'helsinki@example.com', '+358401234567', 10, 'mock data from database'),
(2, 'Restauranto', '456 Market St, Espoo', 'espoo@example.com', '+358402345678', 8, 'mock data from database'),
(3, 'Restauranto', '789 Riverside Rd, Vantaa', 'vantaa@example.com', '+358403456789', 12, 'mock data from database'),
(4, 'Restauranto', '321 Lakeview St, Turku', 'turku@example.com', '+358404567890', 15, 'mock data from database');

-- -----------------------
-- Table `meals`
-- -----------------------
INSERT INTO `meals` (`name_fi`, `name_en`, `description_fi`, `description_en`, `cost`, `image`, `message`) VALUES
('Lihapulla', 'Meatballs', 'Perinteiset lihapullat', 'Classic meatballs', 12.5, 'meatballs.jpg','mock data from database'),
('Lohta', 'Salmon', 'Paistettua lohta perunoilla', 'Fried salmon with potatoes', 15.0, 'salmon.jpg','mock data from database'),
('Kasviskeitto', 'Vegetable Soup', 'Terveellinen kasviskeitto', 'Healthy vegetable soup', 8.0, 'veg_soup.jpg','mock data from database'),
('Kana Curry', 'Chicken Curry', 'Mausteinen kanacurry riisillä', 'Spicy chicken curry with rice', 13.5, 'chicken_curry.jpg','mock data from database'),
('Pasta Bolognese', 'Pasta Bolognese', 'Italialainen bolognese kastike pastan kanssa', 'Italian bolognese sauce with pasta', 11.0, 'pasta_bolognese.jpg','mock data from database'),
('Pizza Margherita', 'Pizza Margherita', 'Perinteinen Margherita pizza', 'Classic Margherita pizza', 10.0, 'pizza_margherita.jpg','mock data from database'),
('Pizza Pepperoni', 'Pizza Pepperoni', 'Pepperonilla täytetty pizza', 'Pepperoni pizza', 12.0, 'pizza_pepperoni.jpg','mock data from database'),
('Caesar Salaatti', 'Caesar Salad', 'Salaatti kanalla ja parmesaanilla', 'Salad with chicken and parmesan', 9.5, 'caesar_salad.jpg','mock data from database'),
('Lasagne', 'Lasagna', 'Italialainen lasagne', 'Italian lasagna', 14.0, 'lasagna.jpg','mock data from database'),
('Kanasalaatti', 'Chicken Salad', 'Kevyt kanasalaatti', 'Light chicken salad', 10.5, 'chicken_salad.jpg','mock data from database'),
('Tomaattikeitto', 'Tomato Soup', 'Terveellinen tomaattikeitto', 'Healthy tomato soup', 7.5, 'tomato_soup.jpg','mock data from database'),
('Hampurilainen', 'Burger', 'Juustohampurilainen', 'Cheeseburger', 11.5, 'burger.jpg','mock data from database'),
('Fish & Chips', 'Fish & Chips', 'Paistettua kalaa ja ranskalaisia', 'Fried fish and chips', 13.0, 'fish_chips.jpg','mock data from database'),
('Sushi Set', 'Sushi Set', 'Assortment of sushi', 'Assortment of sushi', 18.0, 'sushi_set.jpg','mock data from database'),
('Pannukakku', 'Pancake', 'Makea pannukakku', 'Sweet pancake', 6.0, 'pancake.jpg','mock data from database'),
('Ratatouille', 'Ratatouille', 'Kasvisruoka ranskalaisittain', 'French-style vegetable dish', 12.0, 'ratatouille.jpg','mock data from database'),
('Quiche', 'Quiche', 'Perinteinen quiche', 'Traditional quiche', 9.0, 'quiche.jpg','mock data from database'),
('Risotto', 'Risotto', 'Sienirisotto', 'Mushroom risotto', 14.0, 'risotto.jpg','mock data from database'),
('Tortilla', 'Tortilla', 'Täytetty tortilla', 'Stuffed tortilla', 10.0, 'tortilla.jpg','mock data from database'),
('Porkkana-inkiväärikeitto', 'Carrot Ginger Soup', 'Mausteinen porkkana-inkiväärikeitto', 'Spicy carrot ginger soup', 8.0, 'carrot_ginger_soup.jpg','mock data from database'),
('Grillattu Lohi', 'Grilled Salmon', 'Grillattua lohta ja vihanneksia', 'Grilled salmon with vegetables', 16.0, 'grilled_salmon.jpg','mock data from database'),
('Beef Steak', 'Beef Steak', 'Paistettua pihviä', 'Grilled beef steak', 20.0, 'beef_steak.jpg','mock data from database'),
('Veggie Burger', 'Veggie Burger', 'Kasvisburger', 'Vegetarian burger', 11.0, 'veggie_burger.jpg','mock data from database');

-- -----------------------
-- Table `orders`
-- -----------------------
INSERT INTO `orders` (`user`, `cost`, `timestamp`, `message`) VALUES
(1, 25.0, '2025-12-01 12:30:00', 'mock data from database'),
(2, 15.0, '2025-12-02 13:00:00', 'mock data from database'),
(3, 32.0, '2025-12-03 18:45:00', 'mock data from database'),
(4, 45.5, '2025-12-04 19:00:00', 'mock data from database'),
(5, 22.0, '2025-12-05 12:15:00', 'mock data from database'),
(6, 50.0, '2025-12-05 18:00:00', 'mock data from database');


-- -----------------------
-- Table `order_reservations`
-- -----------------------
INSERT INTO `order_reservations` (`order`, `reservation`) VALUES
(1, 1),
(1, 2),
(1, 3),
(2, 4),
(2, 5),
(2, 6),
(3, 7);


-- -----------------------
-- Table `order_gift_cards`
-- -----------------------
INSERT INTO `order_gift_cards` (`order`, `gift_card`) VALUES
(1, 1),
(1, 2),
(1, 3),
(1, 4),
(1, 5),
(1, 6),
(1, 7);


-- -----------------------
-- Table `gift_cards`
-- -----------------------
INSERT INTO `gift_cards` (`value`,`expiration_date`, `password`, message, gift_cards.`order`, `user`) VALUES
(50.0,'2026-01-01', 'GC123','mock data from database', 1,1),
(100.0,'2026-06-30', 'GC456','mock data from database', 1,1),
(75.0,'2026-03-01', 'GC789','mock data from database', 1,1),
(30.0,'2026-05-15', 'GC101','mock data from database', 1,1),
(60.0,'2026-07-20', 'GC102','mock data from database', 1,1),
(120.0,'2026-08-31', 'GC103','mock data from database', 1,1),
(25.0,'2026-10-10', 'GC104','mock data from database', 1,1);

-- -----------------------
-- Table `reservations`
-- -----------------------
INSERT INTO `reservations` (user, `order`, date , table_customer_count, grill_customer_count, message) VALUES
(1,1,'2025-12-05', 1, 2,'mock data from database'),
(1,1,'2025-12-06', 2, 2,'mock data from database'),
(1,1,'2025-12-07', 3, 2,'mock data from database'),
(1,1,'2025-12-08', 4, 2,'mock data from database'),
(1,1,'2025-12-09', 1, 2,'mock data from database'),
(1,1,'2025-12-10', 2, 2,'mock data from database'),
(1,1,'2025-12-11', 3, 2,'mock data from database'),
(1,1,'2025-12-12', 4, 2,'mock data from database'),
(1,1,'2025-12-13', 1, 2,'mock data from database'),
(1,1,'2025-12-14', 2, 2,'mock data from database'),
(1,1,'2025-12-15', 3, 2,'mock data from database'),
(1,1,'2025-12-16', 4, 2,'mock data from database'),
(1,1,'2025-12-17', 1, 2,'mock data from database'),
(1,1,'2025-12-18', 2, 2,'mock data from database'),
(1,1,'2025-12-19', 3, 2,'mock data from database');


-- -----------------------
-- Table `menus`
-- -----------------------
INSERT INTO `menus` (id, date, week ,special_meal, image, message) VALUES
(1,'2025-12-04', 50, 1, 'daily_menu1.jpg', 'mock data from database'),
(2,'2025-12-05', 50, 1, 'daily_menu2.jpg', 'mock data from database'),
(3,'2025-12-06', 50, 1, 'daily_menu3.jpg', 'mock data from database'),
(4,'2025-12-07', 50, 1, 'daily_menu4.jpg', 'mock data from database');

-- -----------------------
-- Table `menu_meals`
-- -----------------------
INSERT INTO `menu_meals` (`menu`, `meal`) VALUES
(1, 1),
(1, 2),
(1, 3),
(2, 4),
(2, 5),
(2, 6),
(3, 7),
(3, 8),
(3, 9),
(4, 10),
(4, 11),
(4, 12);

-- -----------------------
-- Table `discounts`
-- -----------------------
INSERT INTO `discounts` (`id`, discount,`discount_code`, `date_start`, `date_end`, `message`) VALUES
(1, 0.9, 'DISC10', '2025-12-01', '2025-12-31',  'mock data from database'),
(2, 0.9, 'SALMON5', '2025-12-01', '2025-12-31',  'mock data from database'),
(3, 0.9, 'CURRY3', '2025-12-05', '2025-12-20',  'mock data from database'),
(4, 0.9, 'PASTA2', '2025-12-05', '2025-12-25', 'mock data from database'),
(5, 0.9, 'PIZZA5', '2025-12-10', '2025-12-31', 'mock data from database'),
(6, 0.9, 'BURGER5', '2025-12-12', '2025-12-31',  'mock data from database'),
(7, 0.9, 'SUSHI10', '2025-12-01', '2025-12-31',  'mock data from database'),
(8, 0.9, 'RISOTTO5', '2025-12-15', '2025-12-31',  'mock data from database'),
(9, 0.9, 'STEAK10', '2025-12-01', '2025-12-31',  'mock data from database'),
(10, 0.9, 'VEGGIE5', '2025-12-20', '2025-12-31', 'mock data from database');