-- MySQL Script generated by MySQL Workbench
-- Mon Dec  8 02:49:24 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wsk_restaurant_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `role` VARCHAR(50) NULL,
  `name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `image` VARCHAR(100) NULL,
  `message` TEXT NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `meals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meals` ;

CREATE TABLE IF NOT EXISTS `meals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_fi` VARCHAR(100) NULL,
  `name_en` VARCHAR(100) NULL,
  `description_fi` TEXT NULL,
  `cost` FLOAT NULL,
  `type` VARCHAR(50) NULL,
  `description_en` TEXT NULL,
  `image` VARCHAR(100) NULL,
  `message` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orders` ;

CREATE TABLE IF NOT EXISTS `orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` INT NULL DEFAULT NULL,
  `cost` FLOAT NULL DEFAULT NULL,
  `timestamp` DATETIME NULL,
  `message` MEDIUMTEXT NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`));

CREATE INDEX `user_id_in_orders` ON `orders` (`user` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `menus` ;

CREATE TABLE IF NOT EXISTS `menus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `week` INT NULL,
  `special_meal` INT NULL,
  `image` VARCHAR(100) NULL,
  `message` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `menu_meals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `menu_meals` ;

CREATE TABLE IF NOT EXISTS `menu_meals` (
  `menu` INT NOT NULL,
  `meal` INT NOT NULL);

CREATE INDEX `menu_id_in_DMI` ON `menu_meals` (`menu` ASC) VISIBLE;

CREATE INDEX `meal_id_idx` ON `menu_meals` (`meal` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gift_cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gift_cards` ;

CREATE TABLE IF NOT EXISTS `gift_cards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` FLOAT NULL,
  `expiration_date` DATE NULL,
  `password` VARCHAR(100) NULL,
  `order` INT NULL,
  `user` INT NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `user_in_gift_cards_idx` ON `gift_cards` (`user` ASC) VISIBLE;

CREATE INDEX `order_in_gift_cards_idx` ON `gift_cards` (`order` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservations` ;

CREATE TABLE IF NOT EXISTS `reservations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` INT NULL,
  `order` INT NULL,
  `date` DATETIME NULL,
  `table_customer_count` INT NULL,
  `grill_customer_count` INT NULL,
  `message` MEDIUMTEXT NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `user_in_LR_idx` ON `reservations` (`user` ASC) VISIBLE;

CREATE INDEX `order_in_LR_idx` ON `reservations` (`order` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `discounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discounts` ;

CREATE TABLE IF NOT EXISTS `discounts` (
  `id` INT NOT NULL,
  `discount` FLOAT NULL,
  `discount_code` VARCHAR(100) NULL,
  `date_start` DATE NULL,
  `date_end` DATE NULL,
  `message` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `locations` ;

CREATE TABLE IF NOT EXISTS `locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `address` VARCHAR(200) NULL,
  `email` VARCHAR(100) NULL,
  `phone` VARCHAR(100) NULL,
  `table_count` INT NULL,
  `message` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `order_reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `order_reservations` ;

CREATE TABLE IF NOT EXISTS `order_reservations` (
  `order` INT NULL,
  `reservation` INT NULL)
ENGINE = InnoDB;

CREATE INDEX `order_id_in_OrRe_idx` ON `order_reservations` (`order` ASC) VISIBLE;

CREATE INDEX `reservation_id_in_OrRe_idx` ON `order_reservations` (`reservation` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `order_gift_cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `order_gift_cards` ;

CREATE TABLE IF NOT EXISTS `order_gift_cards` (
  `order` INT NOT NULL,
  `gift_card` INT NOT NULL)
ENGINE = InnoDB;

CREATE INDEX `order_id_in_ORGC_idx` ON `order_gift_cards` (`order` ASC) VISIBLE;

CREATE INDEX `gift_card_id_in_ORGC_idx` ON `order_gift_cards` (`gift_card` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
