name: Node.js Full CI

on:
  push:
    branches: ["main"] # Trigger on push to main
  pull_request:
    branches: ["main"] # Trigger on PR targeting main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x] # Test multiple Node versions

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # 3. Install backend dependencies
      - name: Install backend dependencies
        run: npm install

      # 4. Install frontend dependencies
      - name: Install frontend dependencies
        run: npm install --prefix client

      # 5. Build frontend, and prepare public folder
      - name: Build frontend, and prepare public folder
        run: npm run deploy:build

      # 6. Build api documentation
      - name: Build API documentation
        run: npm run apidoc

      # 7. Run tests
      - name: Run backend tests
        run: npm run test
      #- name: Run frontend tests
      #  run: npm test --prefix client
