name: Node.js Full CI

on:
  push:
    branches: ["main"] # Trigger on push to main
  pull_request:
    branches: ["main"] # Trigger on PR targeting main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: testdb
      DB_USER: testuser
      DB_PASSWORD: testpassword
    strategy:
      matrix:
        node-version: [24.x] # Test multiple Node versions

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Start MySQL service
      - name: Start MySQL service
        run: |
          sudo service mysql start
          mysql -u root -proot < database/ciTestDb.sql

      # Setup Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install backend dependencies
      - name: Install backend dependencies
        run: npm install

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: npm install --prefix client

      # Build frontend, and prepare public folder
      - name: Build frontend, and prepare public folder
        run: npm run deploy:build

      # Build api documentation
      - name: Build API documentation
        run: npm run apidoc

      # Run tests
      - name: Run backend tests
        run: npm run test
      #- name: Run frontend tests
      #  run: npm test --prefix client
