### get discounts
GET http://localhost:3000/api/discounts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Im5hbWUiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBlbWFpbC5maSIsInJvbGUiOiJhZG1pbiIsImltYWdlIjoicGxhY2Vob2xkZXIuanBnIiwibWVzc2FnZSI6Im1vY2sgZGF0YSBmcm9tIGRhdGFiYXNlIiwiaWF0IjoxNzY1NDI0NjQ2LCJleHAiOjE3NjU1MTEwNDZ9.RcnXcimQKy53FqonxMkdGwfpBbZHN35omjtlBXwxqbE

### post new discount
POST http://localhost:3000/api/discounts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDY2NzU2NSwiZXhwIjoxNzY0NzUzOTY1fQ.V42nZ5P0krG60ohNoqlaBkn9f-xjcOgcjO1A1i7NXSc

{
  "id" : 5,
  "target_meal": 1,
  "cost_override": 6.9,
  "discount_code" : "just in case getting the discount needs a code",
  "date_start": "some start date",
  "date_end": "some end date",
  "message": "cost_override is the discounted cost"
}

### get discount by id
GET http://localhost:3000/api/discounts/3

### update discount by id
PUT http://localhost:3000/api/discounts/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDU4NTY4MiwiZXhwIjoxNzY0NjcyMDgyfQ.Od8qbnjDXH13TS1CN6DVzOru8AR1DL0Q7gY1kFgo_1U

{
  "id" : 3,
  "target_meal": 6,
  "cost_override": 6.9,
  "discount_code" : "just in case getting the discount needs a code",
  "date_start": "some start date",
  "date_end": "some end date",
  "message": "cost_override is the discounted cost"
}

### delete discount by id
DELETE http://localhost:3000/api/discounts/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidXNlcl9pZCIsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VyIiwiZW1haWwiOiJlbWFpbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDY2NzU2NSwiZXhwIjoxNzY0NzUzOTY1fQ.V42nZ5P0krG60ohNoqlaBkn9f-xjcOgcjO1A1i7NXSc

### gen an array of discounts by sending an array of ids
## returns false for ids not found
POST http://localhost:3000/api/discounts/list/id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Im5hbWUiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBlbWFpbC5maSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTE3NDkzNiwiZXhwIjoxNzY1MjYxMzM2fQ.54PX88Tt0p54w2cjN-2Y6HslSKpqcoRcFG4iPoPVaUw

{
  "discounts" : [3, 2, 0]
}

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsIm5hbWUiOiJuYW1lIiwidXNlcm5hbWUiOiJ1c2VybmFtZSIsImVtYWlsIjoiZGVmYXVsdEBlbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImltYWdlIjoiMTc2NTIzMjUxNTUzNC05NjIwMzcwNTItbGF1dGFuZW4uanBnX3VzZXIud2VicCIsIm1lc3NhZ2UiOiJ1c2VyIG1vZGlmaWVkIGJ5IHVzZXItbW9kZWwiLCJpYXQiOjE3NjU0MjQ0ODYsImV4cCI6MTc2NTUxMDg4Nn0.A_yt1G_8i13HEte9_WE9J3edJw0B0mQMEALE_tGJaxw
### validate discount by discount code
POST http://localhost:3000/api/discounts/validate/STEAK10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Im5hbWUiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBlbWFpbC5maSIsInJvbGUiOiJhZG1pbiIsImltYWdlIjoicGxhY2Vob2xkZXIuanBnIiwibWVzc2FnZSI6Im1vY2sgZGF0YSBmcm9tIGRhdGFiYXNlIiwiaWF0IjoxNzY1NDI0NjQ2LCJleHAiOjE3NjU1MTEwNDZ9.RcnXcimQKy53FqonxMkdGwfpBbZHN35omjtlBXwxqbE
